### ISSUE TITLE
ViaRoute

### ISSUE THREAD

**Issue by ilvits** [custom-components/sensor.yandex_maps#10]
Hi! How  can I add viaPoint? I want to add middle point for my route. May be u write how to create querry for yandex api? Thanks

**Comment by Gan2020** [comment]
Hello! I join the questions above, it would be very useful to put intermediate points.

**Comment by Gan2020** [comment]
Привет! Присоединяюсь к вопросам выше, было бы очень полезно поставить промежуточные точки.
