### ISSUE TITLE
Add ability to avoid tolls roads

### ISSUE THREAD

**Issue by h4** [custom-components/sensor.yandex_maps#11]
Just a copy of comment in PR #7 from @LakMuSer.

**Comment by h4** [comment]
I'm not sure that it is possible in Yandex Maps geohelper api. First of all — because it is undocumented part of http://geohelper.info/ru/doc/api

**Comment by LakMuSer** [comment]
Might be useful
https://yandex.ru/routing/doc/router/concepts/structure.html
https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit-directions/ref/com/yandex/mapkit/directions/driving/DrivingOptions-docpage/

**Comment by h4** [comment]
@LakMuSer this links are related to another Yandex routing project, which is completely different and paid.

**Comment by ludeeus** [comment]
Yeah... let's not even try to get that in here.
Unless there are documented free options, this will cause more issues then what it's worth.
