### ISSUE TITLE
Не правильно определяет время в пути

### ISSUE THREAD

**Issue by colinsn** [custom-components/sensor.yandex_maps#13]
**Version of the custom_component**
0.0.6

**Describe the bug**
Если скопировать в браузер значение атрибута mapurl то открывается карта Ирана с проложенным маршрутом. Если в Яндексе на карте около точки выбрать команду: "Что здесь",то оказываются другие координаты. Такое ощущение что latitude и longitude перевернуты между собой.

**log**

```
Add your logs here.
```

**Comment by pinkkoff** [comment]
+1
