### ISSUE TITLE
Warning No 'version' key in the manifest since HA ver 2021.3.0

### ISSUE THREAD

**Issue by avbor** [custom-components/sensor.yandex_maps#16]
Warning "No 'version' key in the manifest" after update HA to 2021.3.0:
```
No 'version' key in the manifest file for custom integration 'yandex_maps'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'yandex_maps'
```

**Comment by Aldaran** [comment]
Unfortunately, the author has not participated in the life of the project for a long time... Therefore, I can only recommend that you follow my advice. Change your existing manifest (../custom_components/yandex_maps) to:
{
  "domain": "yandex_maps",
  "name": "Yandex Maps",
  "version": "1.0",
  "documentation": "https://github.com/custom-components/sensor.yandex_maps",
  "dependencies": [],
  "codeowners": [],
  "requirements": [],
  "config_flow": false
}

Now I only see 'You are using a custom integration yandex_maps which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant '.
