### ISSUE TITLE
WARNING: Entity sensor.yandex_xxxx implements device_state_attributes. Please report it to the custom component author

### ISSUE THREAD

**Issue by ildar170975** [custom-components/sensor.yandex_maps#19]
**Version of the custom_component**

ef3aa55

HA 2021.12.0

**Describe the bug**

There is a warning in log:
WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.yandex_time_home_person_mama (<class 'custom_components.yandex_maps.sensor.YandexMapsSensor'>) implements device_state_attributes. Please report it to the custom component author.

**log**

```
WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.yandex_time_home_person_mama (<class 'custom_components.yandex_maps.sensor.YandexMapsSensor'>) implements device_state_attributes. Please report it to the custom component author.
```

**Comment by LeoricBY** [comment]
Same here Entity sensor.time_to_home (<class 'custom_components.yandex_maps.sensor.YandexMapsSensor'>) implements device_state_attributes. Please report it to the custom component author.
Warnings after every core restart
