### ISSUE TITLE
mapUrl

### ISSUE THREAD

**Issue by BrownC0de** [custom-components/sensor.yandex_maps#2]
Привет. Отличный компонент, но не хватает "mapUrl": что яндекс отдает в запросе. возможно добавить? Я хочу уже полностью избавиться от REST сенсора.

**Comment by ludeeus** [comment]
I have no clue what anything other than REST and mapUrl means 🤷‍♀️

**Comment by BrownC0de** [comment]
Компонент в итоге получает данный с подобной ссылки? https://yandex.ru/geohelper/api/v1/router?points=32.440835,55.868991~32.034756,55.336536
и забирает от туда time, jamsRate, jamsMeasure. Вот если бы еще от туда забрать mapUrl, то кликая на эту ссылку можно увидеть маршрут, и при желании перейти, и проложить его например в я.навигатор

**Comment by ludeeus** [comment]
What I meant is that I do not understand the language, please use English

**Comment by BrownC0de** [comment]
Oh, i`m sorry )
You use this link https://yandex.ru/geohelper/api/v1/router?points=32.440835,55.868991~32.034756,55.336536 
and take from the result: time, jamsRate, jamsMeasure.
But it would not be bad from this result to take also "mapUrl". This will allow you to get a link with the route on the map, when you navigate to which route to lay out in the navigation application from Yandex.
Which is very convenient to send in the notification, about the time that the road will take.
Sorry for my english. It's all google :)
![screenshot_38](https://user-images.githubusercontent.com/34803844/53742486-c2329200-3ea9-11e9-97a2-aeb08db673c8.png)

**Comment by ludeeus** [comment]
Was implemented by @StanislavBolshakov in #3
