### ISSUE TITLE
It stops working on HASS 0.95.4

### ISSUE THREAD

**Issue by Spirituss** [custom-components/sensor.yandex_maps#6]
**Version of the custom_component**

Yandex maps 0.0.4
Home Assistant 0.95.4
Raspbian Stretch

**Describe the bug**
After upgrade of Home Assistant from version 0.94 to 0.95.4 the sensors of the component stop updating (they are always Unavailable).
There is no any error in HA log file re. the component.

**log**

```
```

**Comment by ludeeus** [comment]
Set logging to `debug` for this.

**Comment by Spirituss** [comment]
What the component name should I specify in ```logger: logs:``` for it in order not to turn on debug mode for all components?

**Comment by ludeeus** [comment]
```
logger:
  default: info
  logs:
    custom_components: debug
```

**Comment by Spirituss** [comment]
It is my fault. Since 0.95 for iOS devices HASS App device_tracker and ```nmap_tracker``` device_tracker for the same device became two different entities. That's why my ```yandex_maps``` component tried to use NMap device tracker GPS coordinates and obviously fails.
Sorry for disturbance! You can close the issue.
