### ISSUE TITLE
Customizable update interval

### ISSUE THREAD

**Issue by Spirituss** [custom-components/sensor.yandex_maps#8]
**Is your feature request related to a problem? Please describe.**
It would be great to add ability to change sensor update interval. At the moment it updates too frequent causing overload of my Raspberry PI and lags of HA web interface.

**Describe the solution you'd like**
To add some control key word to sensor config, like ```update_interval``` with value of the interval in minutes.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by ludeeus** [comment]
use `scan_interval` <https://www.home-assistant.io/docs/configuration/platform_options/#scan-interval>

**Comment by Spirituss** [comment]
Thanks a lot! Great!
