### ISSUE TITLE
Route type

### ISSUE THREAD

**Issue by kasitoru** [custom-components/sensor.yandex_maps#9]
How can I set the route type (by car, on foot, etc.)?

**Comment by ludeeus** [comment]
You can't, every option you can use is described here <https://github.com/custom-components/sensor.yandex_maps#configuration-variables>

**Comment by kasitoru** [comment]
Where was the URL from which the route time information was obtained? On the Internet I could not find documentation on it.

**Comment by ludeeus** [comment]
https://github.com/custom-components/sensor.yandex_maps/blob/master/custom_components/yandex_maps/sensor.py#L23

**Comment by kasitoru** [comment]
You did not understand me. I want to know where this address came from. There is no such API in Yandex documentation.

**Comment by ludeeus** [comment]
Oh.. I don't remember, I think there was a user trying to get help with a rest sensor on discord and I made this instead 🤷‍♂
